# SwiftLint Configuration for Custom Swift Syntax Rules
# This demonstrates how to configure the custom rules in a real SwiftLint setup

# Enable custom SwiftSyntax rules
opt_in_rules:
  - swift_syntax_large_class
  - swift_syntax_too_many_parameters

# Standard SwiftLint rules (for comparison)
enabled_rules:
  - type_body_length
  - function_parameter_count
  - file_length
  - line_length

# Configure custom rules
swift_syntax_large_class:
  max_lines: 150  # Custom threshold (default is 200)
  severity: warning

swift_syntax_too_many_parameters:
  max_parameters: 4  # Custom threshold (default is 5)
  severity: error

# Configure equivalent built-in rules for comparison
type_body_length:
  warning: 150
  error: 200

function_parameter_count:
  warning: 4
  error: 6

# File and line length limits
file_length:
  warning: 400
  error: 1000

line_length:
  warning: 120
  error: 200

# Exclude certain files or directories
excluded:
  - Pods
  - .build
  - Tests
